### PR TITLE
docs(issue-templates): add github issue templates

### PR DESCRIPTION
**Pull request by JayDampitan**
## Changes
1. Added BW S&P github templates

## Purpose
To autofill issue and pull request to make them more consistent

### CODE REVIEW

**Review by BlackCubes — COMMENTED** [review]
Noice my man!!!

**Review by dannysanchez559 — COMMENTED** [review]
Good job Jay

**Review by BlackCubes — APPROVED** [review]
This looks pretty clean. Like how you used BW S&P to be better developers! **Let's go!**

**Review by BlackCubes — COMMENTED** [review]
Jay and I says it looks ok to put into main. Let the games begin!

**Pull request merged**
