### PR TITLE
Userflow 

### LINKED ISSUE #24: Movie app user flow
**Is your feature request related to a problem? Please describe.**
Manipulating elements to enhance user experience flow.
Ex.  movie carousel clutters the U.I. once the user searches a movie term.

**Describe the solution you'd like**
Ex. Removing movie carousel once the user searches a movie term. Testing the rest of the user flow for  issues.

### PR DESCRIPTION
**Pull request by JayDampitan**
## Changes
1. Created a new boolean function that toggles the homepage.
2. Conditionally render carousel and movie list components based on search input and navigating back to homepage. 

## Purpose
_Describe the problem or feature in addition to a link to the issues._
The feature that was added was to help with the transitioning between homepage and movie list to create a seamless single page application.

## Approach
The approach we took was to create a boolean function that renders between homepage and movie list. 

Closes #24

### CODE REVIEW

**Review by connielion — APPROVED** [review]
Looks great so far. Keep up the good work.

**Review by krferrell — APPROVED** [review]
Looks great! Everything is clean.

**Review by Lap343 — APPROVED** [review]
Keeping PRs small. nice

**Review by gonzalespaulb — APPROVED** [review]
Easily readable. LGTM

**Pull request merged**
